apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glitterbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: glitterbot
    spec:
      containers:
        - name: glitterbot
          image: 804879515677.dkr.ecr.us-east-1.amazonaws.com/glitterbot:latest
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: glitterbot
                  key: slack-webhook-url
